server:
  port: 8080
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      mvc:
        routes:
          - id: TICKET-SERVICE
            uri: lb://ticket-service
            predicates:
              - path=/tickets/**
          - id: VEHICLE-SERVICE
            uri: lb://vehicle-service
            predicates:
              - path=/vehicles/**